[project]
name = "nebula-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.14.0",
    "starlette>=1.6.0",
    "tortoise-orm>=1.1.8",
    "uvicorn>=0.53.0",
    "valkey>=6.1.1",
]
